### PR TITLE
Only create regions at functions and loops

### PR DESCRIPTION
**Pull request by lpw25**
This PR changes the placement of regions so that they are only placed around region-locked functions and loop bodies. It makes a number of changes to ensure that calls and blocks are only marked as "tail" if they are in tail position within a lexically enclosing region.

Further changes were needed to make sure that the inserted regions didn't get in the way of existing optimisations. Including:

1. Forcing all default arguments to be global so that the worker-wrapper transformation is always valid.

2. Updating the optimisation of if conditions in cmmgen to push regions downwards.

3. Updating the local functions transformation in simplif to understand tailcalls within regions.

### CODE REVIEW

**Comment by stedolan** [comment]
This patch in general looks good, and the type-system and frontend changes are a welcome simplification.

There are a couple of issues:

  - The Cmm / Selectgen handling in the backend is complicated and I'm not convinced it's correct
  - This PR places a region on essentially every function, even those that contain no local allocations, which increases the code size of `ocamlopt.opt` by around 10%.

I'm working on fixes to both, I'll update this PR soon.

**Comment by lpw25** [comment]
I had planned to add annotations on call sites to say whether they could call a function without an associated region, and then use that to remove most regions in cmm. However, the patch started to get really big and I started to run low on time so I left it. Possibly a solution that avoids creating most of them at lambda time would be better. Happy to leave it to your discretion.

**Comment by stedolan** [comment]
The CI failure in `ephe_infix.ml` on flambda was a real issue: as well as functions and loops, regions are also needed around module-level bindings and in a couple of places in class definitions. Without them, such bindings can leak locally allocated data. In the case of `ephe_infix.ml`, flambda's let-conversion optimisation was promoting a locally allocated value to a static allocation, which confused the GC.

I've pushed a fix to that issue, as well as some tests for the region logic around various syntax forms. I expect there still to be a CI failure on `is_static_flambda.ml`, as the new toplevel regions prevent certain values from being lifted to static allocations.

I have two more patches that need more testing:

  - A more sophisticated check in Lambda to avoid creating most regions, which in particular avoids regions being created around functions that include no local allocations. (I'd like to ensure that in the absence of local allocations, compilation proceeds pretty much as before). This should fix the `is_static_flambda.ml` test, as the regions causing it to fail will be elided.

  - A simplification of the backend changes by removing some optimisations: first, the Cmm `transl_if` region handling should no longer be needed without the redundant regions. Second, I've removed most of the trickiness in selectgen.ml, which was there to handle ending regions early in the case of a `Ctail` which is not in tail position. This optimisation was there to reduce stack usage when functions ending in tail calls are inlined into non-tail position. However, after such inlining the call is no longer a tail call, and we don't do anything special to optimise its space usage on the normal call stack. I see no need to do this optimisation on the local allocation stack either. (Asymptotic complexity is not at stake as we're not in tail position).

I'll post both of these patches next week, then merge.

**Comment by stedolan** [comment]
@lpw25 details in the commit message, but the changes since your patch are:

  - added regions around toplevel expressions (+ some cases of classes, generally anything that uses the exported transl_exp functions from outside translcore)
  - added regions around overapplications with an intermediate local closure (this was a bug previously, such closures leaked)
  - propagate information about whether Lfunctions have regions and the mode of applications all the way through to Cmm level (needed to fix the overapplication bug, because caml_apply splits into two versions)
  - added an optimisation at lambda to remove redundant regions
  - reverted many of the region-manipulation optimisations at Cmm and Selectgen, as they're not necessary with the lambda opts

With the lambda optimisation to remove redundant regions, the 10% code size increase goes away, and the text size of `ocamlopt.opt` is actually slightly smaller with this patch than before.

**Pull request merged**
