### PR TITLE
Avoid registering tuple alloc in parallel let/match

### PR DESCRIPTION
**Pull request by stedolan**
Functions like:
```
let f x y =
  match x, y with
  | p, q -> p + q
```
currently create a pointless region because of the "allocation" of the "tuple" (x, y). Since the typechecker is already tracking these non-tuples-with-tuple-syntax, we may as well avoid counting them as allocations.

### CODE REVIEW

**Comment by lpw25** [comment]
At the moment, I think this will cause the following tuple to be allocated `Alloc_heap`:
```ocaml
let f x y =
  match x, y with
  | p, q -> p + q
  | r -> fst r + 5
```

**Comment by stedolan** [comment]
I've "fixed" that, in a possibly-contentious way, by making `Pexp_var` no longer count as `Maybe_local_tuple`. (I found the half-syntactic check for tuple matches confusing to begin with!)

**Comment by lpw25** [comment]
I'm slightly sad that adding a variable case would lose the higher-precision modes in the other cases. A more important issue though is: do we still need this PR if we are going to stop placing regions based on modes?

**Comment by stedolan** [comment]
We will still be placing regions based on whether or not they contain a local allocation, and functions like the one in the description do not yet by default will contain a region. It's a bit annoying to have a useless save and restore of the stack pointer in such functions.

I find the higher-precision modes in the Pexp_var case a bit hard to understand and explain - in some cases modes are tracked separately per component and sometimes they are not.

**Comment by lpw25** [comment]
I think the function in the description will (only) have an `Lregion` around its body by default. This may or not be removed based on the presence of local allocations during flambda or cmm. The allocation for the tuple will not affect that decision though because it will always be translated out in `matching.ml`. So I don't think this PR will be able to affect the existence of regions in the new approach.

Re the var case It would seem odd to me that:
```ocaml
match x, y with
| Some a, _ -> foo a
| _ -> ()
```
knows that `a` is unaffected by `y`'s mode but
```ocaml
match x, y with
| Some a, _ -> foo a
| p -> bar p
```
doesn't. A criteria that both the tuple pattern and the tuple expression involved must be in tail position within the match makes more sense to me than a criteria that demands that all patterns and expressions in tail position within the match must be tuple patterns.

**Comment by stedolan** [comment]
The new check to remove redundant regions at Lambda in #59 removes the relevant regions here (without any of the caveats around typechecking tuples), so this patch is no longer needed.

**Pull request closed without merging**
